### ISSUE TITLE
about Product Page's title

### ISSUE THREAD

**Issue by keithshih** [feegleweb/octoshop-theme#1]
i want to change product page's title = product name & model , how can i do ? thanks!

**Comment by dshoreman** [comment]
You can get the name and model with `{{ product.title }}` and `{{ product.model }}` respectively. For more information on how you can incorporate that into layouts and pages, check the October docs.

**Comment by keithshih** [comment]
Thank's

but, I failed...

I can't get the current product id or name or...   in product page

how to get this value? when I click the product list page's product item

hope you know my bad english ...

my [CMS][PAGE] code : product.htm
------------------------------------------------
title = "product"
url = "/product/:slug"
layout = "default"
hidden = "0"
[shopProduct]
slug = "{{ :slug }}"
basket = "#minibasket"
mainImageSize = "556"
subImageSize = "116"



= =
<?php
function onStart()
{
        
  $this['product_name'] = DB::table('feegleweb_octoshop_products')->select('first_name')->where('id',   ????  )->first();

  $this->page->title = $this['product_name'];
}

?>
= =
<div class=" row">
    <div class="col-md-6 col-sm-6">
.................
